Artist profile
music-for-all/music-for-all-application pull request #92
Opened 2016-10-24 10:22 UTC by excaliware

This update includes:
- an artist profile page
- a few UI improvements
- new sample audio files
- refactored code

2016-10-25 16:52 UTC, cat-eat-dog requested changes

2016-10-25 16:52 UTC, cat-eat-dog commented on application/src/main/java/com/musicforall/model/Track.java
> +                        " from History history" +
why it's in main application?

2016-10-25 16:52 UTC, cat-eat-dog commented on application/src/main/java/com/musicforall/web/profile/ProfileController.java
> +        model.addAttribute("user", SecurityUtil.currentUser());
better to use some kind of dto and fill it with nonsensetive data

2016-10-25 17:04 UTC, excaliware commented on application/src/main/java/com/musicforall/model/Track.java
> +                        " from History history" +
Are you implying that it should be in the History?

2016-10-25 17:08 UTC, excaliware commented on application/src/main/java/com/musicforall/web/profile/ProfileController.java
> +        model.addAttribute("user", SecurityUtil.currentUser());
I don't quite understand what you want here.

2016-10-27 10:39 UTC, cat-eat-dog commented on application/src/main/java/com/musicforall/model/Track.java
> +                        " from History history" +
yes. every query related to history should be in history module.

2016-10-27 10:43 UTC, cat-eat-dog commented on application/src/main/java/com/musicforall/web/profile/ProfileController.java
> +        model.addAttribute("user", SecurityUtil.currentUser());
instead of using enitity class for User its better to create UserDto and use it everywhere there is a need to pass user instance to front-end

2016-10-27 10:44 UTC, cat-eat-dog commented on application/src/main/java/com/musicforall/web/profile/ProfileController.java
> +    public String artistProfile(Model model, @PathVariable String name) {
better to have separate controller for artists` profiles

2016-11-30 15:47 UTC, merged